// <auto-generated />
using CityInfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityInfo.API.Migrations
{
    [DbContext(typeof(CityInfoDbContext))]
    [Migration("20240824175029_InitialDataSeed")]
    partial class InitialDataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "It is small peaceful semi urban area located in the morang district.",
                            Name = "Gothgaun"
                        },
                        new
                        {
                            Id = 2,
                            Description = "It is the beautiful place located in the satdobato, lalitpur.",
                            Name = "Nakhipot"
                        },
                        new
                        {
                            Id = 3,
                            Description = "It is city located in the Sunsari district and important business hub of eastern Nepal.",
                            Name = "Itahari"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointOfInterests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "The PU is situated here.",
                            Name = "Purbanchal University"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "The oldest government school in the gothgaun.",
                            Name = "Panchayat School"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "Kirat Yakthung Chumlung is a social organization of the Limbu indigenous ethnic group of Nepal.",
                            Name = "Kirat Yakthung Chumlung"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Description = "Ullens School is a private school in Nepal that offers holistic education from Kindergarten to IBDP.",
                            Name = "Ullens School"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 2,
                            Description = "It is the biggest goods store in the Satdobato.",
                            Name = "Bhatbhateni Store"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 3,
                            Description = "It is the oldest department store in the Itahari.",
                            Name = "Gorkha Department"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 3,
                            Description = "It is a distinguished educational institution nestled in the heart of Itahari Sunsari.",
                            Name = "Namuna College"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.HasOne("CityInfo.API.Entities.City", "City")
                        .WithMany("PointOfInterests")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Navigation("PointOfInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
